version: '3'

services:
  
  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:3.7.5
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
      - '15672:15672'
  
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    hostname: server
    volumes:
      - ./server:/src
      - ./server/bulk_extractor:/usr/share/bulk_extractor
      - ./data:/data
    ports:
      - '8000:8000'
    command: >
      bash -c '
      python3 manage.py migrate &&
      daphne -b 0.0.0.0 -p 8000 server.asgi:application'
    depends_on:
      - rabbitmq
      - redis
  
  worker:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/src
      - ./server/bulk_extractor:/usr/share/bulk_extractor
      - ./data:/data
    command: celery -A server worker -l info
    depends_on:
      - rabbitmq
      - redis
